import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { MarketingService } from './marketing.service';

/**
 * "Dá vida" ao Marketing IA: 1x/dia, analisa produtos novos, gera o próximo
 * dia do calendário (o Calendar Agent já rotaciona produtos sozinho) e anexa
 * imagem a cada post novo. Mesmo padrão do `SocialScheduler` (setInterval em
 * processo, sem Redis/cron externo).
 *
 * Diferente do `MarketingPublishScheduler`: aqui nada é publicado de verdade
 * (só gera conteúdo no calendário), então o padrão é LIGADO — desligue com
 * `MARKETING_AUTO_GENERATE=false` se preferir só os cliques manuais.
 */
@Injectable()
export class MarketingAutoScheduler {
  private readonly logger = new Logger(MarketingAutoScheduler.name);
  private static readonly CHECK_INTERVAL_MS = 60 * 60 * 1000;
  private lastRunDate = '';
  private timer: ReturnType<typeof setInterval> | null = null;

  constructor(
    private readonly config: ConfigService,
    private readonly marketing: MarketingService,
  ) {}

  start(): void {
    if (!this.config.get<boolean>('social.marketingAutoGenerate')) {
      this.logger.log(
        'Geração automática do Marketing IA desativada (MARKETING_AUTO_GENERATE=false).',
      );
      return;
    }
    void this.tick();
    this.timer = setInterval(() => void this.tick(), MarketingAutoScheduler.CHECK_INTERVAL_MS);
    this.logger.log('Geração automática do Marketing IA ativa.');
  }

  stop(): void {
    if (this.timer) clearInterval(this.timer);
  }

  private async tick(): Promise<void> {
    const now = new Date();
    const today = now.toISOString().slice(0, 10);
    const generateHour = this.config.get<number>('social.marketingGenerateHour') ?? 6;
    if (this.lastRunDate === today || now.getHours() < generateHour) return;

    this.lastRunDate = today; // marca antes de tentar: não reprocessa na mesma hora em caso de erro
    const ownerId = this.config.get<string>('telegram.ownerId') ?? 'bras';

    try {
      const result = await this.marketing.autoGenerateDaily(ownerId);
      this.logger.log(
        `Geração automática diária: ${result.analyzed} produto(s) analisado(s), ` +
          `${result.created} post(s) criado(s), ${result.imagesAttached} imagem(ns) anexada(s).`,
      );
    } catch (err) {
      this.logger.error(`Falha na geração automática diária do Marketing IA: ${String(err)}`);
    }
  }
}
